version: '3'
services:
cjmaster:
image: djmaster
volumes:
- C:\Jmeter\DockerImage\dockjm\Results:/Results
- C:\Jmeter\DockerImage\dockjm\TestScripts:/TestScripts
command: tail -f /dev/null
ports:
- "45000:8086"
links:
- influxdb
cjslave1:
image: djslave
links:
- influxdb
cjslave2:
image: djslave
links:
- influxdb
influxdb:
image: influxdb:1.7.4
ports:
- "8086:8086"
environment:
- INFLUXDB_DB=jmeter
- INFLUXDB_ADMIN_ENABLED=true
- INFLUXDB_ADMIN_USER=admin
- INFLUXDB_ADMIN_PASSWORD=admin123
- INFLUXDB_USER=jmeter
- INFLUXDB_USER_PASSWORD=jmeter123
grafana:
image: grafana/grafana:10.0.3
ports:
- "3000:3000"
environment:
- GF_SECURITY_ADMIN_PASSWORD=admin
links:
- influxdb