FROM jbase

WORKDIR $JMETER_HOME/bin

# Ports to be exposed from the container for JMeter Slaves/Server
EXPOSE 1099 50000

# Application to run on starting the container
ENTRYPOINT $JMETER_HOME/bin/jmeter-server -Dserver.rmi.localport=50000 -Dserver_port=1099 -Jserver.rmi.ssl.keystore.file=$JMETER_HOME/bin/rmi_keystore.jks